### ISSUE TITLE
No me detecta los ODControl V1 Firmware 1.6.3

### ISSUE THREAD

**Issue by axpirina** [opalenzuela/opendomo-automation#31]
Plugin Automation instalado.

Llegando a "Configure"-"Manage Control Devices" y "Add"  he metido las credenciales de los OD (username-pass-IP..)    y me da el error "Cannot connect to the especified devide" .

Trabajando en red local con el Opendomo recien instalado en la Raspberry Pi.

Un empujoncito para averiguar que estoy haciendo mal?
 
Gracias

**Comment by opalenzuela** [comment]
¿Lo estás probando con la 2.1 o con la beta de la 2.2?

**Comment by axpirina** [comment]
Lo estoy probando con la 2.1
Soy recien llegado al Github pero ya me hice el trabajito de leerme todos los issues cerrados. Lo que no he encontrado es la forma de instalar el beta 2.2.

Hay alguna apt-get install para ello?

Estoy dispuesto a probar con la 2.2

**Comment by opalenzuela** [comment]
En este hilo puedes encontrar la imagen a la Beta 2.2 para Raspberry PI: https://github.com/opalenzuela/opendomo/issues/77

En cualquier caso, la versión estable está al caer. Si esperas un poco te ahorrarás tener que actualizar!

**Comment by axpirina** [comment]
Perfecto!

**Comment by axpirina** [comment]
He instalado el Beta y por lo que respecta a la interfaz me gusta mucho!

Aún y todo sigo sin poder añadir los ODControl a la lista de los "Control Device".

He intentado poner la de administrador de Opendomo y tambien la pass de administrador de ODControl pero nada de nada.

"The Device Cannot Be Edited" es el mensaje.

Parece pues que encuentra un device en esa dirección pero es incapaz de editar el enlace. 

Notifico para que lo tengais en cuenta a la hora de sacar la versión estable.

PD: A las ODControl, y la opendomo puedo entrar sin problemas, independientemente, en red local

**Comment by aitorantonanzas** [comment]
por si sirve de algo a mi tampoco me agregar los odcontrol como dispositivo.

Cannot connect to the specified device

addControlDevice.sh:Not formatted line

ODCGI BUILD: Jan 21 2015 14:28:57
	UID: 1000 
	GID: 1000 
	CGI_SERVER_PROTOCOL: HTTP/1.1
	CGI_SERVER_PORT: 80
	CGI_REQUEST_METHOD: POST
	CGI_PATH_INFO: /addControlDevice.sh
	CGI_PATH_TRANSLATED: 
	CGI_SCRIPT_NAME: /cgi-bin/od.cgi
	CGI_QUERY_STRING: 
	CGI_REMOTE_HOST: 
	CGI_REMOTE_IDENT: 
	CGI_CONTENT_TYPE: application/x-www-form-urlencoded
	CGI_CONTENT_LENGTH: 81
	CGI_DECODED_URL: type=odcontrol&username=admin&password=opendomo&ipaddress=192.168.0.11&refresh+=5

**Comment by opalenzuela** [comment]
@jmirasb Al tratarse de una versión 1.6 sería interesante que lo verificaras tú. Creo recordar que el binding para ODControl1.6 funcionaba bien...

**Comment by axpirina** [comment]
Probando con el ODEnergy(primera versión) y me lo agrega sin problemas como dispositivo. 

Todavia no logró que me agrege los ODControl V1.
 
ERROR - "La operación no pudo completarse"


Opendomo 2.2 Beta + (4x) ODControl 1.6.3 + ODEnergy

**Comment by opalenzuela** [comment]
Relacionado con #23 . Vamos a probar de hacerlo a mano.

1. Crea un archivo de configuración para uno de los ODControl, llamémosle "odc01", con el siguiente formato:

/etc/opendomo/control/odc01.conf

     URL='192.168.1.11'
     USER='user'
     PASS='opendomo'
     TYPE='odcontrol'
     REFRESH='5'
     DEVNAME='odc01'

Una vez lo tengas, ejecuta los siguientes comandos:

     /usr/local/opendomo/daemons/odauto.sh stop
     touch /var/opendomo/run/odauto.pid
     /usr/local/opendomo/bindings/odcontrol.sh /etc/opendomo/control/odc01.conf

¿Qué salida obtienes?

**Comment by axpirina** [comment]
En esto de linux soy nuevo. O sea he empezado hoy :-D y creo que el proceso de aprendizaje me llevara mas de los cinco minutillos de rigor. Me empollare al menos los terminos y comandos en finde.

En esta hora he intentado editar el odc01.conf con gedit y con nano usando la terminal pero no he tenido suerte. Por lo menos he apuntado la lista de directorios del sistema tambien y me los empollare el finde. Asi voy poniendome un poco en el tema. 

El lunes cuando llegue al curro lo intento otra vez con algún consejo del administrador de redes.

Cuando cree el archivo odc01.conf de la forma que me dices y ejecute los comando que hay arriba ya escribiré la salida que visualizo.

No vemos el lunes y muchas gracias por el apoyo! Iré pasito a pasito :-D

**Comment by opalenzuela** [comment]
@axpirina No te preocupes, te echaremos un cable en lo que sea posible!

Mi consejo: no sé si trabajas con máquina virtual o si lo haces sobre Raspberry PI, pero si tu PC de trabajo es Windows, necesitarás instalarte Putty.exe para acceder por terminal SSH. Sí, incluso en la máquina virtual, porque te permitirá copiar y pegar los comandos y obtener la salida. 

OpenDomoOS no lleva ni "nano" ni "gedit", únicamente "vi", pero para escribir texto dentro de un archivo, mi consejo es usar la redirección de la salida estándar:

    cat > /etc/opendomo/control/odc01.conf
    URL='192.168.1.11'
    USER='user'
    PASS='opendomo'
    TYPE='odcontrol'
    REFRESH='5'
    DEVNAME='odc01'
    (aquí deberás pulsar CTRL+D para terminar la edición)

**Comment by aitorantonanzas** [comment]
@opalenzuela a mi me sale el siguiente error despues de haber seguido los pasos que comentas.

admin@OpenDomoOS:/etc/opendomo/control$ /usr/local/opendomo/bindings/odcontrol.sh /etc/opendomo/control/odc01.conf
-bash: /usr/local/opendomo/bindings/odcontrol.sh: /bin/sh^M: bad interpreter: No such file or directory

**Comment by opalenzuela** [comment]
Vale, el problema está claro. El binding está roto por una cuestión de formato... Déjame revisarlo y te aviso en cuanto lo tenga solucionado!

**Comment by opalenzuela** [comment]
Si estás trabajando con el proyecto de Github ya está corregido. Si no, debería solucionarse con la próxima actualización.

**Comment by opalenzuela** [comment]
@aitorantonanzas  ¿Lo pudiste probar con la 2.2?

**Comment by aitorantonanzas** [comment]
@opalenzuela No e podido probarlo aún.  Te aviso en cuanto lo haga.

**Comment by joakinmr** [comment]
Buenas tardes,  acabo de añadir a la versión 2.2 estable dos ODC 1.6.3 y los he podido agregar correctamente, decir que lo hago desde fuera de mi red, pero que aunque sí me deja añadirlo, los puertos no me salen. A la hora entrar a la configuración de puertos obtengo lo siguiente (en modo gráfico)

192168122
content=width=device-width,
href=http
initial-scale=1,
maximum-scale=1>
name=viewport
rel=apple-touch-icon
rel=stylesheet

**Comment by opalenzuela** [comment]
@jmirasb ¿Podrías validar este punto? Creo recordar que esto funcionaba y no hemos hecho cambios al respecto...

**Comment by axpirina** [comment]
Pues yo sigo sin poder agregarlos :-C

ODCGI BUILD: Feb  9 2015 15:05:25
	UID: 1000 
	GID: 1000 
	CGI_SERVER_PROTOCOL: HTTP/1.1
	CGI_SERVER_PORT: 80
	CGI_REQUEST_METHOD: POST
	CGI_PATH_INFO: /addControlDevice.sh
	CGI_PATH_TRANSLATED: 
	CGI_SCRIPT_NAME: /cgi-bin/od.cgi
	CGI_QUERY_STRING: 
	CGI_REMOTE_HOST: 
	CGI_REMOTE_IDENT: 
	CGI_CONTENT_TYPE: application/x-www-form-urlencoded
	CGI_CONTENT_LENGTH: 66
	CGI_DECODED_URL: type=odcontrol&password=opendomo&ipaddress=192.168.0.14&refresh+=5


4 ODControl 1.6.3 y OpendomoOS V2.2.4 en la Raspi B y  todos los plugin.

**Comment by opalenzuela** [comment]
Hemos subido una actualización del plugin que parece que finalmente soluciona este problema. En cuanto se te aplique la actualización deberás volver a configurar los dispositivos para que los reconozca.

**Comment by joakinmr** [comment]
Gracias equipo, por cierto, hablando de actualizar, sigo con la versión 2.2.3, en que directorio está el script Script updateSystem.sh?

**Comment by opalenzuela** [comment]
Debería estar en el path. Si quieres lanzarlo a mano, entra como "admin" al terminal y escribe "updateSystem.sh". Tardará unos cuantos minutos pero debería terminar por actualizar. Guarda cambios y reinicia de vez en cuando, por si acaso!

**Comment by joakinmr** [comment]
Eso pensaba, pero desde el terminar no lo lanza. Bueno ya lo busco.

**Comment by axpirina** [comment]
He conseguido conectarlos usando como dirección el http://1xx.xxx.x.xx:81

Ahora el juego esta en como activar o desactivar una salida. Aqui hay mucho tomate pa mi

Pasito a paso

**Comment by axpirina** [comment]
gracias antonanas!!

**Comment by opalenzuela** [comment]
Damos por cerrado este hilo pues. Gracias por la ayuda!
